version: '2'
services:
  metamaskver:
    image: metamaskverig
    container_name: metamaskverig
    restart: always
    ports:
      - "62000:8080"
    volumes:
       - ./logs/:/root/.pm2/logs/
       - ./codefolder/:/usr/codefolder/
    environment:
      LANG: C.UTF-8
    
