version: '2'
services:
  metamaskver:
    image: metamaskverign
    container_name: metamaskverign
    restart: always
    ports:
      - "62001:8080"
    volumes:
       - ./logs/:/root/.pm2/logs/
       - ./codefolder/:/usr/codefolder/
    environment:
      LANG: C.UTF-8
    
